import { semanticKeywords, WikimediaImageProvider } from "../services/ImageProvider.js";
import * as THREE from "../vendor/three.module.js";

const TAU = Math.PI * 2, CORNERS = [0, 1, 2, 0, 2, 3];
const clamp = (value, min = 0, max = 1) => Math.max(min, Math.min(max, value));
const randomFrom = seed => { let state = (seed * 0xffffffff) >>> 0; return () => { state += 0x6d2b79f5; let value = state; value = Math.imul(value ^ value >>> 15, value | 1); value ^= value + Math.imul(value ^ value >>> 7, value | 61); return ((value ^ value >>> 14) >>> 0) / 4294967296; }; };

export function getDreamPhotoQuality(width, dpr = 1, cores = 4) {
  if (width < 520 || cores <= 4) return { name: "LOW", count: 6, textureSize: 256 };
  if (width < 960 || width * dpr < 1400 || cores <= 6) return { name: "MEDIUM", count: 8, textureSize: 256 };
  return { name: "HIGH", count: 12, textureSize: 256 };
}

export function createAsteroidPlan(composition, count) {
  const random = randomFrom((composition.seed + composition.signature * .173) % 1);
  return Array.from({ length: count }, (_, index) => ({
    seed: random(), radius: .45 + random() * 1.6, aspect: index % 10 < 7 ? 1 : index % 10 < 9 ? .66 + random() * .2 : .82 + random() * .28,
    orbit: .65 + random() * 2.2, phase: random() * TAU, x: (random() - .5) * 5.6, y: (random() - .5) * 3.4, z: -1.1 - random() * 7.6,
    roll: random() * TAU, tilt: (random() - .5) * 1.35, speed: .018 + random() * .035, alpha: .2 + random() * .16,
    life: 38 + random() * 45, age: random() * 26, sourceIndex: index, recycleQueued: false
  })).map(item => ({ ...item, homeZ: item.z })).sort((a, b) => a.z - b.z);
}

export const DREAM_PHOTO_VERTEX = `attribute vec3 aPosition;attribute vec2 aUv;attribute float aAlpha;uniform vec2 uView;varying vec2 vUv;varying float vAlpha;mat2 rot(float a){float c=cos(a),s=sin(a);return mat2(c,-s,s,c);}void main(){vec3 p=aPosition;p.xz=rot(uView.x)*p.xz;p.yz=rot(uView.y)*p.yz;float d=max(.3,-p.z);float depth=.1+.84*smoothstep(.3,9.5,d);gl_Position=vec4(p.x/3.1,p.y/1.75,(depth*2.-1.)*d,d);vUv=aUv;vAlpha=aAlpha;}`;
const FRAGMENT = `precision mediump float;uniform sampler2D uAtlas;uniform float uDrift;varying vec2 vUv;varying float vAlpha;void main(){vec4 photo=texture2D(uAtlas,vUv);float l=dot(photo.rgb,vec3(.299,.587,.114));vec3 drift=vec3(.008,-.004,.012)*sin(uDrift+l*2.);vec3 glow=photo.rgb+smoothstep(.62,1.,l)*.055;gl_FragColor=vec4(glow+drift,photo.a*vAlpha);}`;

export class DreamPhotoLayer {
  constructor(provider = new WikimediaImageProvider()) { this.provider = provider; this.enabled = true; this.items = []; this.sources = []; this.elapsed = 0; this.generation = 0; }
  init(scene, renderer, camera) { this.scene = scene; this.renderer = renderer; this.camera = camera; this.gl = renderer.gl; this.geometry = new THREE.PlaneGeometry(2, 2); this.material = { type: "DreamPhotoMaterial" }; this.handleOnline=()=>{if(this.composition&&!this.sources.length)this.loadResonantImages(this.generation);};window.addEventListener("online",this.handleOnline,{passive:true});if (scene) scene.dreamPhotoLayer = this; this.setupGl(); }
  setupGl() { const gl=this.gl;if(!gl)return;const compile=(type,source)=>{const shader=gl.createShader(type);gl.shaderSource(shader,source);gl.compileShader(shader);return shader;};this.program=gl.createProgram();gl.attachShader(this.program,compile(gl.VERTEX_SHADER,DREAM_PHOTO_VERTEX));gl.attachShader(this.program,compile(gl.FRAGMENT_SHADER,FRAGMENT));gl.linkProgram(this.program);this.buffer=gl.createBuffer();this.texture=gl.createTexture();this.data=new Float32Array(12*6*6); }
  setEmojiState(composition, quality) {
    if (!composition || !this.gl) return; const generation=++this.generation;this.items.forEach(item=>this.scene.remove(item.mesh));this.composition=composition;this.quality=quality;this.items=createAsteroidPlan(composition,quality.count);this.items.forEach(item=>{item.mesh=new THREE.Mesh(this.geometry,this.material);this.scene.add(item.mesh);});this.columns=4;this.rows=Math.ceil(quality.count/4);this.createFallbackAtlas();this.loadResonantImages(generation);
  }
  createFallbackAtlas() { const size=this.quality.textureSize,canvas=document.createElement("canvas");canvas.width=this.columns*size;canvas.height=this.rows*size;const ctx=canvas.getContext("2d");this.items.forEach((item,index)=>this.paintFallback(ctx,index,item));this.uploadAtlas(canvas); }
  paintFallback(ctx,index,item) { const size=this.quality.textureSize,x=index%this.columns*size,y=Math.floor(index/this.columns)*size,color=this.composition.palette[index%4].map(v=>Math.round(v*255));ctx.clearRect(x,y,size,size);const gradient=ctx.createRadialGradient(x+size*.42,y+size*.38,size*.03,x+size*.5,y+size*.5,size*.49);gradient.addColorStop(0,`rgba(${color},.54)`);gradient.addColorStop(.55,`rgba(${color},.22)`);gradient.addColorStop(1,`rgba(${color},0)`);ctx.fillStyle=gradient;ctx.fillRect(x,y,size,size); }
  uploadAtlas(canvas) { const gl=this.gl;gl.bindTexture(gl.TEXTURE_2D,this.texture);gl.pixelStorei(gl.UNPACK_PREMULTIPLY_ALPHA_WEBGL,true);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,canvas);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE); }
  async loadResonantImages(generation) { try { const terms=semanticKeywords(this.composition.symbols,this.composition.seed),sources=await this.provider.search(terms,Math.max(24,this.items.length*2));if(generation!==this.generation)return;this.sources=sources;for(let index=0;index<this.items.length&&generation===this.generation;index++){if(!sources.length)break;await this.replaceCell(index,sources[index%sources.length],generation);} } catch(error) { if(error?.name!=="AbortError"&&generation===this.generation)this.sources=[]; } }
  async replaceCell(index,source,generation=this.generation) { let bitmap;try{bitmap=await this.provider.preload(source);if(generation!==this.generation)return;const canvas=this.createDreamTexture(bitmap,this.items[index]);const gl=this.gl;gl.bindTexture(gl.TEXTURE_2D,this.texture);gl.texSubImage2D(gl.TEXTURE_2D,0,index%this.columns*this.quality.textureSize,Math.floor(index/this.columns)*this.quality.textureSize,gl.RGBA,gl.UNSIGNED_BYTE,canvas);}catch{}finally{this.provider.release(bitmap);} }
  createDreamTexture(image,item) { const size=this.quality.textureSize,canvas=document.createElement("canvas");canvas.width=canvas.height=size;const ctx=canvas.getContext("2d"),random=randomFrom(item.seed),zoom=1.45+random()*1.65,side=Math.min(image.width,image.height)/zoom,sx=(image.width-side)*random(),sy=(image.height-side)*random(),blur=Math.min(5,Math.max(1.2,(420/side-1)*1.8));ctx.filter=`blur(${blur}px) saturate(1.18) contrast(1.06)`;ctx.drawImage(image,sx,sy,side,side,-4,-4,size+8,size+8);ctx.filter="none";ctx.globalCompositeOperation="screen";const glow=ctx.createRadialGradient(size*.42,size*.38,0,size*.42,size*.38,size*.45);glow.addColorStop(0,"rgba(255,245,230,.13)");glow.addColorStop(1,"rgba(255,255,255,0)");ctx.fillStyle=glow;ctx.fillRect(0,0,size,size);ctx.globalCompositeOperation="destination-in";const mask=ctx.createRadialGradient(size*.5,size*.5,size*.12,size*.5,size*.5,size*(.45+random()*.05));mask.addColorStop(0,"rgba(255,255,255,.98)");mask.addColorStop(.62,"rgba(255,255,255,.82)");mask.addColorStop(.88,"rgba(255,255,255,.24)");mask.addColorStop(1,"rgba(255,255,255,0)");ctx.fillStyle=mask;ctx.fillRect(0,0,size,size);return canvas; }
  update(delta,audio={},interaction={},view={x:0,y:0}) { if(!this.enabled||!this.items.length)return;this.elapsed+=delta;let offset=0;const energy=audio.energy||0,mid=audio.mid||0,dx=(interaction.x??.5)-.5,dy=(interaction.y??.5)-.5;for(let index=0;index<this.items.length;index++){const item=this.items[index];item.age+=delta*(1+mid*.08);item.z+=(item.homeZ-item.z)*(1-Math.exp(-delta*.075));const phase=item.phase+this.elapsed*item.speed*(1+energy*.09),fadeIn=clamp(item.age/4),fadeOut=clamp((item.life-item.age)/7),alpha=item.alpha*fadeIn*fadeOut*(1+energy*.08);if(item.age>item.life&&!item.recycleQueued)this.recycleAsteroid(index);const influence=(interaction.strength||0)*Math.exp(-Math.hypot(item.x/3-dx,item.y/2-dy)*2.3),x=item.x+Math.sin(phase)*item.orbit*.28+dx*influence*.28,y=item.y+Math.cos(phase*.73)*item.orbit*.13+dy*influence*.22,z=item.z+Math.sin(phase*.41)*.45+(audio.low||0)*.12;const breathe=1+energy*.025,size=item.radius*breathe,roll=item.roll+this.elapsed*item.speed*.28,tilt=item.tilt+Math.sin(phase*.37)*.22,c=Math.cos(roll),s=Math.sin(roll),ct=Math.cos(tilt),st=Math.sin(tilt),mesh=item.mesh;mesh.position.x=x;mesh.position.y=y;mesh.position.z=z;mesh.rotation.y=tilt;mesh.rotation.z=roll;mesh.scale.x=size;mesh.scale.y=size*item.aspect;const col=index%this.columns,row=Math.floor(index/this.columns),u0=col/this.columns,u1=(col+1)/this.columns,v0=row/this.rows,v1=(row+1)/this.rows;for(let vertex=0;vertex<6;vertex++){const corner=CORNERS[vertex],right=corner===1||corner===2,top=corner>=2,lx=(right?1:-1)*size,ly=(top?1:-1)*size*item.aspect,rx=lx*c-ly*s,ry=lx*s+ly*c;this.data[offset++]=x+rx*ct;this.data[offset++]=y+ry;this.data[offset++]=z+rx*st;this.data[offset++]=right?u1:u0;this.data[offset++]=top?v0:v1;this.data[offset++]=alpha;}}this.draw(offset,view); }
  recycleAsteroid(index) { const item=this.items[index];item.recycleQueued=true;item.age=0;item.z=-8.5;item.phase+=2.1;item.recycleQueued=false;if(this.sources.length){item.sourceIndex=(item.sourceIndex+this.items.length)%this.sources.length;this.replaceCell(index,this.sources[item.sourceIndex]);} }
  draw(length,view) { const gl=this.gl;gl.useProgram(this.program);gl.bindBuffer(gl.ARRAY_BUFFER,this.buffer);gl.bufferData(gl.ARRAY_BUFFER,this.data,gl.DYNAMIC_DRAW);const stride=24,bind=(name,count,offset)=>{const location=gl.getAttribLocation(this.program,name);gl.enableVertexAttribArray(location);gl.vertexAttribPointer(location,count,gl.FLOAT,false,stride,offset);};bind("aPosition",3,0);bind("aUv",2,12);bind("aAlpha",1,20);gl.uniform2f(gl.getUniformLocation(this.program,"uView"),view.x||0,view.y||0);gl.uniform1f(gl.getUniformLocation(this.program,"uDrift"),this.elapsed*.035);gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,this.texture);gl.uniform1i(gl.getUniformLocation(this.program,"uAtlas"),0);gl.enable(gl.DEPTH_TEST);gl.depthMask(false);gl.enable(gl.BLEND);gl.blendFunc(gl.ONE,gl.ONE_MINUS_SRC_ALPHA);gl.drawArrays(gl.TRIANGLES,0,length/6);gl.disable(gl.BLEND);gl.depthMask(true); }
  resize(width,dpr){this.viewport={width,dpr};} setEnabled(enabled){this.enabled=Boolean(enabled);} dispose(){this.generation++;window.removeEventListener("online",this.handleOnline);this.provider.dispose();this.items.forEach(item=>this.scene?.remove(item.mesh));this.geometry?.dispose();if(!this.gl)return;this.gl.deleteBuffer(this.buffer);this.gl.deleteTexture(this.texture);this.gl.deleteProgram(this.program);if(this.scene?.dreamPhotoLayer===this)delete this.scene.dreamPhotoLayer;this.items=[];this.sources=[];}
}
